/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c5",
        "background": "#f9f9f9",
        "secondary-fixed-dim": "#dec65a",
        "surface-container": "#eeeeee",
        "primary-container": "#1b1b1b",
        "on-secondary-fixed": "#211b00",
        "on-error-container": "#93000a",
        "surface": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "on-tertiary-fixed": "#1c1b1b",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "error-container": "#ffdad6",
        "tertiary-container": "#1c1b1b",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "surface-variant": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-background": "#1a1c1c",
        "on-primary-fixed-variant": "#474747",
        "on-tertiary-fixed-variant": "#474746",
        "inverse-surface": "#2f3131",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-container": "#848484",
        "surface-dim": "#dadada",
        "outline-variant": "#cfc4c5",
        "surface-container-high": "#e8e8e8",
        "inverse-primary": "#c6c6c6",
        "on-secondary-container": "#736200",
        "outline": "#7e7576",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#5e5e5e",
        "on-primary-fixed": "#1b1b1b",
        "on-tertiary-container": "#858383",
        "on-secondary-fixed-variant": "#534600",
        "secondary": "#6e5e00",
        "error": "#ba1a1a",
        "tertiary-fixed": "#e5e2e1",
        "secondary-container": "#f8df71",
        "secondary-fixed": "#fbe273"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        display: ["Hanken Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
};
